apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-1-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jisna-testingmavens/infra-repo-env.git
    targetRevision: main
    path: helm/ms-1
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
