apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-1-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jisna-testingmavens/ms-1.git
    path: helm/ms-1
    targetRevision: main
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

