apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-1-stg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<org>/infra.git
    path: helm/ms-1
    targetRevision: main
    helm:
      valueFiles:
        - values-stg.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
